import k from "./terms.module.css"


const TermsandConditions = () => {
  return (<div className={`${k.root} " m-5 p-4 dark:bg-bdark bg-primary"`}>
    <h1 className="dark:text-primary">TERMS OF SERVICE</h1>
    <h2 className="dark:text-gray-200 text-newblack/90">DATED: MAY 2022</h2>
    <p className="text-newblack/90 dark:text-primary">The Penthouse service and network (collectively, the “<strong>Service</strong>“) are operated by Penthouse Finance, and its affiliates (collectively, the “<strong>Company</strong>“, “<strong>we</strong>“, or “<strong>us</strong>“). By accessing or using our website at <a href="https://penthouse.finance">penthouse.finance</a>&nbsp;including any subdomain thereof (the “<strong>Site</strong>“), you (the “<strong>User</strong>“) signify that you have read, understand and agree to be bound by these terms of use (“<strong>Terms of Use</strong>“), regardless of whether you are a registered member of the Service. In addition to these Terms of Use, you may enter into other agreements with us or others that will govern your use of the Service or related services offered by us or others. If there is any contradiction between these Terms of Use and another agreement you enter into applicable to specific aspects of the Service, the other agreement shall take precedence in relation to the specific aspects of the Service to which it applies. As used herein, “<strong>Users</strong>” means anyone who accesses and/or uses the Site. For any terms herein applicable to all Users, all investor members, or business and other entity Users specifically, or where the context otherwise requires, “Users” shall be deemed to include any business or other entity on behalf of which the Site or Service is accessed by any other User, and “you” shall be deemed to include any such business or other entity and any person acting on behalf of any such business or other entity in connection with the use of the Site or Service.</p>
    <h3 className="text-newblack/90 dark:text-primary">‍Changes to these Terms of Use</h3>
    <p className="text-newblack/90 dark:text-primary">We may make changes to these Terms of Use from time to time. If we do this, we will post the changed Terms of Use on the Site and will indicate at the top of this page the date the Terms of Use were last revised. You understand and agree that your continued use of the Service or the Site after we have made any such changes constitutes your acceptance of the new Terms of Use.</p>
    <h2 className="dark:text-gray-200 text-newblack/90">TERMS APPLICABLE TO ALL USERS: ELIGIBILITY, LICENSE AND REPRESENTATIONS</h2>
    <h3 className="text-newblack/90 dark:text-primary">Eligibility: General</h3>
    <p className="text-newblack/90 dark:text-primary">‍This Site is intended solely for Users who, if they are a natural person, are eighteen (18) years of age or older, and any registration by, use of or access to the Site by any natural person under 18 is unauthorized, unlicensed and in violation of these Terms of Use. By using the Service or the Site, you represent and warrant that, if you are a natural person, you are 18 or older and that you agree to and will abide by all of the terms and conditions of these Terms of Use. If you violate any of these Terms of Use, or otherwise violate an agreement between you and us, the Company may delete your profile and any content or information that you have posted on the Site and/or prohibit you from using or accessing the Service or the Site (or any portion, aspect or feature of the Service or the Site), at any time in its sole discretion, with or without notice, including without limitation if it believes that you are under 18.</p>
    <h3 className="text-newblack/90 dark:text-primary">Proprietary Rights in Site Content; Limited License</h3>
    <p className="text-newblack/90 dark:text-primary">The Website may include at any given time text, graphics, logos, icons, images, sound clips, video clips and data compilations, and together with the Website’s page layout, underlying code and software we refer to all of these as “Content”.</p>
    <p className="text-newblack/90 dark:text-primary">All of the Content is the property of Penthouse Finance, our affiliates or third parties with whom we do business, and this means that it is protected by United States and international intellectual property laws and other relevant laws. This means that, except as provided by law, you may not reproduce, copy, distribute, store or in any other fashion re-use material from the Website unless otherwise indicated on the Website or unless given express written permission to do so by Penthouse Finance. For the avoidance of doubt, data mining or scraping the Website without the express written permission of Penthouse Finance is not permitted.</p>
    <h3 className="text-newblack/90 dark:text-primary">Restrictions on Data Collection/Termination</h3>
    <p className="text-newblack/90 dark:text-primary">Without our prior consent, you may not</p><ul className="dark:text-primary">
       <li>– use any automated means to access this Site or collect any information from the Site (including, without limitation, robots, spiders, scripts or other automatic devices or programs);</li>
       <li>– frame the Site, utilize framing techniques to enclose any Content or other proprietary information, place pop-up windows over this Site’s pages, or otherwise affect the display of this Site’s pages; engage in the practices of “screen scraping”, “database scraping” or any other activity with the purpose of obtaining content or other information;</li>
       <li> -use this Site in any manner that violates applicable law or that could damage, disable, overburden, or impair this Site or interfere with any other party’s use and enjoyment of this Site.</li>
    </ul>
    <p className="text-newblack/90 dark:text-primary">We may terminate, disable or throttle your access to, or use of, this Site and the Services for any reason, including without limitation, if we believe that you have violated or acted inconsistently with any portion of these Terms of Use.</p>
    ‍<h3 className="dark:text-primary">User Representations</h3>
    <p className="text-newblack/90 dark:text-primary">You represent, warrant and agree that no materials of any kind submitted through your account or otherwise posted or shared by you through the Service will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libelous, defamatory or otherwise unlawful material. You further agree not to harvest or collect email addresses or other contact information of Users from the Service or the Site by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications. Additionally, you agree not to use automated scripts to collect information from the Service or the Site or for any other purpose. You further agree that you may not use the Service or the Site in any unlawful manner or in any other manner that could damage, disable, overburden or impair the Site. In addition, you agree not to use the Service or the Site to:</p>
    <ul className="dark:text-primary">
<li>– upload, post, transmit, share, store or otherwise make available any content that we deem to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable</li>
<li>
– except where authorized by the Company, register for more than one User account, register for a User account on behalf of an individual other than yourself, operate a User account on behalf of or for the benefit of any person who is not eligible to register for or operate a User account in their own name, or register for a User account on behalf of any group or entity (other than approved investment accounts opened on behalf of legal entities)</li>
<li>
– impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with or authority to act on behalf of any person or entity</li>
<li>
– upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising, solicitations, promotional materials, “junk mail”, “spam”, “chain letters”, “pyramid schemes”, or any other form of solicitation</li>
<li>
– upload, post, transmit, share, store or otherwise make publicly available on the Site any private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Security numbers and credit card numbers</li>
<li>
– solicit personal information from any natural person under 18 or solicit passwords or personally identifying information for commercial or unlawful purposes from any User</li>
<li>
– upload, post, transmit, share or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment</li>
<li> intimidate or harass another User</li>
<li>
– upload, post, transmit, share, store or otherwise make available content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law</li>
<li>
– use or attempt to use another’s account, service or system without authorization from that person and the Company, or create a false identity on the Service or the Site</li>
<li>
– upload, post, transmit, share, store or otherwise make available content that, in the sole judgment of the Company, is objectionable or which restricts or inhibits any other person from using or enjoying the Site, or which may expose the Company or its Users to any harm or liability of any type.</li>
    </ul>
    <h3 className="text-newblack/90 dark:text-primary">User Content Posted on the Site</h3>
    <p className="text-newblack/90 dark:text-primary">By posting User Content to any part of the Site, you automatically grant, and you represent and warrant that you have the right to grant, to the Company an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with the right to sublicense) to use, copy, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part) and distribute such User Content for any purpose on or in connection with the Site or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize sublicenses of the foregoing. You may remove your User Content from the Site at any time. If you choose to remove your User Content, the license granted above will not expire.</p>
    <p className="text-newblack/90 dark:text-primary">You may review personal or business information posted by other Users on the Site, but you are not authorized to disclose such information for any purpose.</p>
    <h3 className="text-newblack/90 dark:text-primary">‍ALL USERS: CONSENT TO ELECTRONIC TRANSACTIONS AND DISCLOSURES</h3>
    <p className="text-newblack/90 dark:text-primary">Because Penthouse Finance operates on the Internet, it is necessary for you to consent to transact business with us online and electronically. As part of doing business with us, therefore, we also need you to consent to our giving you certain disclosures electronically, either via our Site or to the email address (or other electronic means of communication) you provide to us. By agreeing to the Terms of Use, you agree to receive electronically all documents, communications, notices, contracts, and agreements (including any IRS Forms, including Form 1099 and Form K-1) arising from or relating to your use of the Site and Service, including any securities you have purchased, your use of this Service, and the voting of any securities you have purchased as an investor in any offering made available through the Site (each, a “<strong>Disclosure</strong>“), whether we are acting in the capacity as issuer, agent or otherwise. The decision to do business with us electronically is yours. This document informs you of your rights concerning Disclosures.</p>
    <p className="text-newblack/90 dark:text-primary">Electronic Communications. Any Disclosures will be provided to you electronically through Penthouse Finance either on our Site or via electronic mail to the verified email address you provided or through other electronic means of communication based on information provided by you. If you require paper copies of such Disclosures, you may write to us at the mailing address provided below and a paper copy will be sent to you at a cost of up to $5.00. A request for a paper copy of any Disclosure will not be considered a withdrawal of your consent to receive Disclosures electronically. Any IRS 1099 Forms or Form K-1s provided electronically will remain accessible through at least October 15 of the year in which such IRS Form 1099 or Form K-1 is made available; after that time the IRS Form 1099 may no longer be accessible electronically. We may discontinue electronic provision of Disclosures at any time in our sole discretion.</p>
    <p className="text-newblack/90 dark:text-primary">Scope of Consent. Your consent to receive Disclosures and transact business electronically, and our agreement to do so, applies to any transactions to which such Disclosures relate, whether between you and Penthouse Finance or between you and another party with whom you transact through the Site. Your consent will remain in effect for so long as you are a User and, if you are no longer a User, will continue until such a time as all Disclosures relevant to transactions that occurred while you were a User have been made.</p>
    <p className="text-newblack/90 dark:text-primary">Consenting to Do Business Electronically. Before you decide to do business electronically with Penthouse Finance, you should consider whether you have the required hardware and software capabilities described below.</p>
    <p className="text-newblack/90 dark:text-primary">Hardware and Software Requirements. In order to access and retain Disclosures electronically, you must satisfy the following computer hardware and software requirements: access to the Internet; an email account and related software capable of receiving email through the Internet; supported Web browsing software (Chrome version 32.0 or higher, Firefox version 26.0 or higher, Internet Explorer version 8.0 or higher, or Safari version 7.0 or higher); and hardware capable of running this software.</p>
    <p className="text-newblack/90 dark:text-primary">Telephone Consumer Protection Act Overview Consent: You expressly consent to receiving calls and messages, including auto-dialed and pre-recorded message calls, and SMS messages (including text messages) from us, our affiliates, agents and others calling at their request or on their behalf, at any telephone numbers that you have provided or may provide in the future (including any cellular telephone numbers). Your cellular or mobile telephone provider will charge you according to the type of plan you carry.</p>
    <p className="text-newblack/90 dark:text-primary">Consent to Digital Call Recording. Penthouse Finance uses technology that records telephone calls for quality assurance, customer service, training and data analysis purposes only. By agreeing to our Terms of Use, you hereby consent to our recording of telephone conversations between you and Penthouse Finance representatives and you hereby agree that our employees and authorized representatives may listen to a call that has been recorded on our behalf for the purposes set forth above.</p>
    <p className="text-newblack/90 dark:text-primary">To unsubscribe from text messages at any time reply STOP, STOP ALL, UNSUBSCRIBE, CANCEL, END or QUIT to any text message you receive from Penthouse Finance. You consent that following such a request to unsubscribe, you may receive one final text message from Penthouse Finance confirming your request. Note that unsubscribing from promotional and/or account-related texts will not prevent Penthouse Finance from sending you text messages for security and authentication purposes.</p>
    <p className="text-newblack/90 dark:text-primary">Additional Mobile Technology Requirements. If you are accessing our site and the Disclosures electronically via a mobile device (such as a smart phone, tablet, and the like), in addition to the above requirements you must make sure that you have software on your mobile device that allows you to print and save the Disclosures presented to you during the application process. These applications can be found for most mobile devices in the device’s respective “app store”. If you do not have these capabilities on your mobile device, please access our site through a device that provides these capabilities.</p>
    <p className="text-newblack/90 dark:text-primary">Withdrawing Consent. You may not withdraw consent to doing business with us electronically for as long as you have outstanding any investments made through the Site. If you have no outstanding investments made through the site and wish to withdraw consent to doing business electronically, we will terminate your registered user account with us.</p>
    <p className="text-newblack/90 dark:text-primary">How to Contact Us regarding Electronic Disclosures. You can contact us via email at <a href="mailto:hello@penthouse.finance">hello@penthouse.finance</a></p>
    <p className="text-newblack/90 dark:text-primary">If you are an individual User, you will keep us informed of any change in your email or home mailing address so that you can continue to receive all Disclosures in a timely fashion. If your registered email address changes, you must notify us of the change by sending an email to&nbsp;<a href="mailto:hello@penthouse.finance">hello@penthouse.finance</a>. You also agree to update your registered residence address and telephone number on the Site if they change. If you are a business or entity User or are acting on behalf of a business or entity, you will keep us informed of any change to your email address, telephone number and primary business address, as discussed under “Terms Applicable to Business and Other Entity Users” below.</p>
    <p className="text-newblack/90 dark:text-primary">You will print a copy of this Agreement for your records and you agree and acknowledge that you can access, receive and retain all Disclosures electronically sent via email or posted on the Site.</p>
    <h3 className="text-newblack/90 dark:text-primary">SECURITIES MATTERS</h3>
    <p className="text-newblack/90 dark:text-primary">Notwithstanding anything to the contrary in these Terms of Use, in no event shall anything in these Terms of Use be deemed to be a waiver, and we will not assert there has been a waiver, that would not be permissible under Section 14 of the Securities Act of 1933, Section 29(a) of the Securities Exchange Act of 1934, or any other applicable provision of federal and state securities laws.</p>
    <p className="text-newblack/90 dark:text-primary">Investment overviews and so-called “tombstone” advertisements on the Site may contain summaries of the principal features or terms of investment opportunities available through the Site. Such overviews and tombstone advertisements are intended for informational purposes only and do not purport to be complete, and each is qualified in its entirety by reference to the more detailed discussions contained in the Offering Circular filed with the Securities and Exchange Commission or other offering materials relating to such investment opportunity.&nbsp;<strong>YOU MUST CAREFULLY REVIEW THE RELEVANT OFFERING CIRCULAR AND OR OTHER OFFERING MATERIALS BEFORE DECIDING TO INVEST</strong>. The information contained on the Site has been prepared by Penthouse Finance without reference to any particular user’s investment requirements or financial situation, and potential investors are encouraged to consult with professional tax, legal and financial advisors before making any investment.</p>
    <p className="text-newblack/90 dark:text-primary">The terms of our offerings preclude you from becoming a beneficial owner of 25% or more of any issuer’s outstanding equity securities. You represent that you will not attempt to circumvent this policy and you understand that each issuer will be entitled pursuant to its operating agreement to unwind or not recognize your beneficial ownership in excess of such threshold.</p>
    <h2 className="dark:text-gray-200 text-newblack/90">TERMS APPLICABLE TO INDIVIDUAL USERS</h2>
    <h3 className="text-newblack/90 dark:text-primary">Registration Data; Account Security</h3>
    <p className="text-newblack/90 dark:text-primary">In consideration of your use of the Site, you agree to (a) provide accurate, current and complete information about you as may be prompted by any registration or subscription forms on the Site or otherwise requested by the Company (“<strong>Individual Registration Data</strong>“); (b) maintain the security of your password and identification; (c) maintain and promptly update the Individual Registration Data, and any other information you provide to the Company, to keep it accurate, current and complete; (d) promptly notify the Company regarding any material changes to information or circumstances that could affect your eligibility to continue to use the Site or Service or the terms on which you use the Site or Service; and (e) be fully responsible for all use of your account and for any actions that take place using your account.</p>
    <h2 className="dark:text-gray-200 text-newblack/90">TERMS APPLICABLE TO BUSINESS AND OTHER ENTITY USERS</h2>
    <h3 className="text-newblack/90 dark:text-primary">Eligibility: Business and Other Entity Users</h3>
    <p className="text-newblack/90 dark:text-primary">Access to the Site for Users that are businesses, other entities or persons acting on behalf of such businesses or entities, is intended solely for authorized representatives of businesses or other entities that are in good standing in each jurisdiction in which they are registered to conduct business and persons otherwise authorized by such businesses or entities to act in furtherance of the business or entity’s use of the Site or Service. By using the Service or the Site on behalf of a business or other entity, you represent and warrant that you are duly authorized in accordance with the foregoing by the business or other entity on behalf of which you are acting, that you have the power and authority to enter into binding agreements on behalf of the business or entity or in the capacity in which you are acting, and that the business or entity is in good standing in each jurisdiction in which it is registered to conduct business to the best of your knowledge. Furthermore, you confirm that you agree to all of the terms and conditions of these Terms of Use individually and on behalf of such business or other entity, and represent and warrant that you and such business or other entity will abide by all of the terms and conditions of these Terms of Use. If you, the business or entity, any other person acting on behalf of the business or entity or any guarantor (if applicable) violate any of these Terms of Use, or otherwise violate an agreement between the business or entity (or, if applicable, any guarantor) and the Company, the Company may terminate the business or entity’s membership, delete any associated profile and any content or information posted on the Site in connection with the business or entity’s membership and/or prohibit you, such business or entity and any other person acting on the business or entity’s behalf from using or accessing the Service or the Site (or any portion, aspect or feature of the Service or the Site), at any time in its sole discretion, with or without notice.</p>
    ‍<h3 className="dark:text-primary"><strong>Business Registration Data; Account Security<br />‍</strong></h3>
    <p className="text-newblack/90 dark:text-primary">In consideration of your use of the Site and the Service on behalf of a business or other entity member, you, individually and on behalf of such business or entity, agree to (a) provide accurate, current and complete information about the business or entity, yourself and any other principals and/or authorized representatives of the business or entity member as may be prompted by any registration forms on the Site or otherwise requested by the Company (“<strong>Business Registration Data</strong>“), including the business or entity’s full legal name; (b) provide such materials as the Company may request to establish and/or verify your or any other person’s identity or authority to enter into binding agreements on behalf of the business or entity, or to establish and/or verify the business or entity’s legal existence, good standing in any jurisdiction and eligibility to use the Site or Service; (c) maintain the security of any password and identification issued for use by or on behalf of the business or entity; (d) maintain and promptly update the Business Registration Data, and any other information provided to the Company by you or anyone else acting on behalf of the business or entity, to keep it accurate, current and complete; (e) promptly notify the Company regarding any material changes to information or circumstances impacting the business or entity’s legal existence, good standing in any jurisdiction in which the business or entity is authorized to conduct business, or eligibility for continued use of the Site or any Service; and (f) be fully responsible for all use of any accounts opened on behalf of the business or entity and for any actions that take place using such account.</p>
    <h3 className="text-newblack/90 dark:text-primary">‍Additional Representations: Business and Other Entity Users</h3>
    <p className="text-newblack/90 dark:text-primary">In addition to the User Representations set forth above under “User Representations”, which you hereby confirm on behalf of the business or entity member, you further agree, both individually and on behalf of the business or entity, not to use the Service or the Site to:</p>
    <ul className="dark:text-primary">
<li>– register for multiple User accounts on behalf of the same business or entity</li>
<li> operate or otherwise utilize an account opened in the name of a business or entity for the benefit of any persons other than that business or entity</li>
<li>
– operate or otherwise utilize an account opened in the name of a business or entity for any purpose prohibited by law or regulation, any activity which that business or entity is not duly authorized to conduct, or for any purpose prohibited by any other agreement between the business or entity and the Company or Our Affiliates</li>
<li>
– operate a User account on behalf of any business or entity with regard to which you are not an authorized person with the power to enter into binding agreements on behalf of the business or entity</li>
<li>
– communicate with any other User regarding the business or entity, or it’s business operations, other than anonymously and publicly via the Site, or upload, post, transmit, share or otherwise make available any information or informational material identifying the business or entity or its business operations (other than Business Registration Data provided to the Company or other information requested by the Company or otherwise necessary for your use of the Site or Service)</li>
<li> and
– upload, post, transmit, share, store or otherwise make publicly available on the Site any private information regarding the business or entity, including, without limitation, addresses, phone numbers, email addresses, tax identification numbers and credit, or any personal information regarding persons associated with the business or entity (other than Business Registration Data provided to the Company).</li>
    </ul>
    <p className="mt-3 dark:text-primary">Furthermore, you represent and warrant and agree, both individually and on behalf of the business or entity, that:</p>
    <ul className="dark:text-primary">
<li>– all email addresses provided on behalf of the business or entity are and will be used by the business or entity for business purposes</li>
<li> and
– you will not represent or portray the business or entity as being affiliated with the Company in any capacity other than being a User of the Site or Service without the Company’s prior written consent.</li>
</ul>
    <h3 className="text-newblack/90 dark:text-primary">‍Scope of License to Use</h3>
    <p className="text-newblack/90 dark:text-primary">‍For Users that are businesses or other entities, or persons acting on behalf of businesses or other entities, the limited license to access and use the Site granted above shall be deemed granted to the business or entity member and to those authorized representatives of the business or entity for whom Business Registration Data has been provided to the Company while acting on behalf of the business or entity member in their official capacities. Any access to or use of the Site by persons who are not authorized representatives of the business or entity, including but not limited to any representative for whom Business Registration Data has not been provided, voids this license and shall constitute a violation of these Terms of Use. Furthermore, this license is revocable by us at any time with regard to the business or entity member and/or any person acting on such business or entity’s behalf without notice and with or without cause.</p>
    <h2 className="dark:text-gray-200 text-newblack/90">ALL USERS: INTELLECTUAL PROPERTY MATTERS</h2>
    <h3 className="text-newblack/90 dark:text-primary">‍Trademarks</h3>

    <p className="text-newblack/90 dark:text-primary">Penthouse Finance and other Company graphics, logos, designs, page headers, button icons, scripts and service names are registered trademarks, trademarks or trade dress of the Company in the USA and/or other countries. The Company’s trademarks and trade dress may not be used, including as part of trademarks and/or as part of domain names, in connection with any product or service in any manner that is likely to cause confusion and may not be copied, imitated, or used, in whole or in part, without the prior written permission of the Company.</p>
    ‍<h3 className="dark:text-primary">Copyright Complaints</h3>
    <p className="text-newblack/90 dark:text-primary">If you believe that any material on the Site infringes upon any copyright which you own or control, you may send a written notification of such infringement to our Designated Agent as set forth below:</p>
    <p className="text-newblack/90 dark:text-primary">Name of Agent Designated to Receive Notification of Claimed Infringement: Attention: General Counsel</p>
    <p className="text-newblack/90 dark:text-primary">E-Mail Address of Designated Agent:&nbsp;<a href="mailto:hello@penthouse.finance">hello@penthouse.finance</a></p>
    <p className="text-newblack/90 dark:text-primary">To meet the notice requirements under the Copyright, Designs and Patents Act 1988, the notification must be a written communication that includes the following:</p>
    <ul className="dark:text-primary">
<li>– A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed</li>
<li>
– Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site</li>
<li>
– Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material</li>
<li>
– Information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number and, if available, an electronic mail address at which the complaining party may be contacted</li>
<li>
– A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law</li>
<li> and
– A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
    </ul>
    <h3 className="text-newblack/90 dark:text-primary">Repeat Infringer Policy</h3>
    <p className="text-newblack/90 dark:text-primary">‍In accordance with The Copyright, Designs and Patents Act 1988 and other applicable law, the Company has adopted a policy of terminating, in appropriate circumstances and at the Company’s sole discretion, the memberships of members who are deemed to be repeat infringers. The Company may also at its sole discretion limit access to the Site and/or terminate the memberships of any Users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.</p>
   <h3 className="text-newblack/90 dark:text-primary"> ‍Submissions</h3>
    <p className="text-newblack/90 dark:text-primary">You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Site or the Service (“<strong>Submissions</strong>“), provided by you to the Company are non-confidential and shall become the sole property of the Company. The Company shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
    <h3 className="text-newblack/90 dark:text-primary">User Disputes</h3>
    <p className="text-newblack/90 dark:text-primary">You are solely responsible for your interactions with other Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users.</p>
    <h3 className="text-newblack/90 dark:text-primary">Privacy</h3>
    <p className="text-newblack/90 dark:text-primary">Please review the Site’s Privacy Policy. By using the Site or the Service, you are consenting to have your personal data transferred to and processed in the United States. We may listen to and/or record phone calls between you and our representatives without notice to you as permitted by applicable law. For example, we listen to and record calls for quality monitoring purposes.</p>
    <h3 className="text-newblack/90 dark:text-primary">‍Disclaimers</h3>
    <p className="text-newblack/90 dark:text-primary">The Company does not guarantee the accuracy of any User Content or Third Party Content. Although we provide rules for User conduct and postings, we do not control and are not responsible for what Users post on the Site and are not responsible for any offensive, inappropriate, obscene, unlawful or otherwise objectionable content you may encounter on the Site or in connection with any User Content or Third Party Content. The Company is not responsible for the conduct, whether online or offline, of any User of the Site or Service. The Company cannot guarantee and does not promise any specific results from use of the Site and/or the Service.</p>
    <p className="text-newblack/90 dark:text-primary">The Site and the Service may be temporarily unavailable from time to time for maintenance or other reasons. The Company assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, User communications. The Company is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or on the Site or combination thereof, including injury or damage to Users or to any other person’s computer related to or resulting from participating or downloading materials in connection with the Web and/or in connection with the Service. Under no circumstances will the Company be responsible for any loss or damage, including any loss or damage to any User Content, financial damages or lost profits, loss of business, or personal injury or death, resulting from anyone’s use of the Site or the Service, any User Content or Third Party Content posted on or through the Site or the Service or transmitted to Users, or any interactions between Users of the Site, whether online or offline.</p>
    <p className="text-newblack/90 dark:text-primary">The Company reserves the right to change any and all content contained in the Site and any Services offered through the Site at any time without notice. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof, or any affiliation therewith, by the Company.</p>
    <h3 className="text-newblack/90 dark:text-primary">Limitation on Liability</h3>
    <p className="text-newblack/90 dark:text-primary">EXCEPT IN JURISDICTIONS WHERE SUCH PROVISIONS ARE RESTRICTED AND EXCEPT AS PROVIDED ABOVE IN THE SECTION TITLED, “SECURITIES MATTERS”, IN NO EVENT WILL THE COMPANY OR ITS DIRECTORS, EMPLOYEES OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA ARISING FROM YOUR USE OF THE SITE OR THE SERVICE OR ANY OF THE SITE CONTENT OR OTHER MATERIALS ON OR ACCESSED THROUGH THE SITE, EVEN IF THE COMPANY IS AWARE OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
    <p className="text-newblack/90 dark:text-primary">NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN EXCEPT AS PROVIDED ABOVE IN THE SECTION TITLED, “SECURITIES MATTERS”, TO THE EXTENT PERMITTED BY APPLICABLE LAW THE COMPANY’S LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO THE COMPANY FOR THE SERVICE DURING THE TERM OF MEMBERSHIP. IN NO CASE, EXCEPT AS PROVIDED ABOVE IN THE SECTION TITLED, “SECURITIES MATTERS”, WILL THE COMPANY’S LIABILITY TO YOU EXCEED $1000. YOU ACKNOWLEDGE THAT IF NO FEES ARE PAID TO THE COMPANY FOR THE SERVICE, YOU SHALL BE LIMITED TO INJUNCTIVE RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND SHALL NOT BE ENTITLED TO DAMAGES OF ANY KIND FROM THE COMPANY, REGARDLESS OF THE CAUSE OF ACTION.</p>
    <p className="text-newblack/90 dark:text-primary">IN ADDITION TO THE SPECIFIC SECURITIES LAWS PROVISIONS DESCRIBED ABOVE IN THE SECTION TITLED, “SECURITIES MATTERS”, CERTAIN FEDERAL AND STATE LAWS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES OR LIMITATIONS ON IMPLIED WARRANTIES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS. s### Governing Law; Venue and Jurisdiction; Arbitration</p>
    <p className="text-newblack/90 dark:text-primary">By visiting or using the Site and/or the Service, you agree that the laws of the State of Delaware, without regard to any principles of conflict of laws that would require or permit the application of the laws of any other jurisdiction, will govern these Terms of Use. By agreeing to the Terms of Use and using the Website and the Service, you agree to agree to the binding arbitration provisions set forth in these Terms of Use and submit to personal jurisdiction in the Federal courts located in Florida for all purposes, and you agree to waive, to maximum extent permitted by law, any right to a trial by jury for any matter.</p>
    <p className="text-newblack/90 dark:text-primary">Either party may, at its sole election, require that the sole and exclusive forum and remedy for resolution of a Claim be final and binding arbitration. The arbitration shall be conducted in US. As used in this provision, “Claim” shall include any past, present, or future claim, dispute, or controversy involving you (or persons claiming through or connected with you), on the one hand, and Penthouse Finance (or officers, directors, employees, contractors, managers, members or other persons claiming through or connected with Penthouse Finance), on the other hand, relating to or arising out of the Site, the Services, these Terms of use and/or the activities or relationships that involve, lead to, or result from any of the foregoing, including the validity or enforceability of this arbitration provision, provided that this provision shall not apply to any Claims arising under Federal securities laws. Claims are subject to arbitration regardless of whether they arise from the contract; tort (intentional or otherwise); a constitution, statute, common law, or principles of equity; or otherwise. Claims include (without limitation) matters arising as initial claims, counter-claims, cross-claims, third-party claims, or otherwise. The scope of this arbitration provision is to be given the broadest possible interpretation that is enforceable.</p>
    <p className="text-newblack/90 dark:text-primary">The party initiating arbitration shall do so in the State of Delaware. The arbitration shall be conducted according to, and the location of the arbitration shall be determined in accordance with, the rules and policies of the administrator selected, except to the extent the rules conflict with this arbitration provision or any countervailing law. In the case of a conflict between the rules and policies of the administrator and this arbitration provision, this arbitration provision shall control, subject to countervailing law, unless all parties to the arbitration consent to have the rules and policies of the administrator apply.</p>
    <p className="text-newblack/90 dark:text-primary">If we elect arbitration, we shall pay all the administrator’s filing costs and administrative fees (other than hearing fees). If you elect arbitration, filing costs and administrative fees (other than hearing fees) shall be paid in accordance with the rules of the administrator selected, or in accordance with countervailing law if contrary to the administrator’s rules. We shall pay the administrator’s hearing fees for one full day of arbitration hearings. Fees for hearings that exceed one day will be paid by the party requesting the hearing, unless the administrator’s rules or applicable law require otherwise, or you request that we pay them and we agree to do so. Each party shall bear the expense of its own attorney’s fees, except as otherwise provided by law. If a statute gives you the right to recover any of these fees, these statutory rights shall apply in the arbitration notwithstanding anything to the contrary herein.</p>
    <p className="text-newblack/90 dark:text-primary">Within 30 days of a final award by the arbitrator, a party may appeal the award for reconsideration by a three-arbitrator panel selected according to the rules of the arbitrator administrator. In the event of such an appeal, an opposing party may cross-appeal within 30 days after notice of the appeal. The panel will reconsider de novo all aspects of the initial award that are appealed. Costs and conduct of any appeal shall be governed by this arbitration provision and the administrator’s rules, in the same way as the initial arbitration proceeding. Any award by the individual arbitrator that is not subject to appeal, and any panel award on appeal, shall be final and binding, except for any appeal right under the Federal Arbitration Act (the “FAA”), and may be entered as a judgment in any court of competent jurisdiction.</p>
    <p className="text-newblack/90 dark:text-primary">We agree not to invoke our right to arbitrate an individual Claim that you may bring in Small Claims Court or an equivalent court, if any, so long as the Claim is pending only in that court. EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT, NO ARBITRATION SHALL PROCEED ON A CLASS, REPRESENTATIVE, OR COLLECTIVE BASIS (INCLUDING AS PRIVATE ATTORNEY GENERAL ON BEHALF OF OTHERS), EVEN IF THE CLAIM OR CLAIMS THAT ARE THE SUBJECT OF THE ARBITRATION HAD PREVIOUSLY BEEN ASSERTED (OR COULD HAVE BEEN ASSERTED) IN A COURT AS CLASS REPRESENTATIVE, OR COLLECTIVE ACTIONS IN A COURT.</p>
    <p className="text-newblack/90 dark:text-primary">Unless otherwise provided in these Terms of Use or consented to in writing by all parties to the arbitration, no party to the arbitration may join, consolidate, or otherwise bring claims for or on behalf of two or more individuals or unrelated corporate entities in the same arbitration unless those persons are parties to a single transaction. Unless consented to in writing by all parties to the arbitration, an award in arbitration shall determine the rights and obligations of the named parties only, and only with respect to the claims in arbitration, and shall not (i) determine the rights, obligations, or interests of anyone other than a named party, or resolve any Claim of anyone other than a named party, or (ii) make an award for the benefit of, or against, anyone other than a named party. No administrator or arbitrator shall have the power or authority to waive, modify, or fail to enforce this provision, and any attempt to do so, whether by rule, policy, arbitration decision or otherwise, shall be invalid and unenforceable. Any challenge to the validity of this provision shall be determined exclusively by a court and not by the administrator or any arbitrator.</p>
    <p className="text-newblack/90 dark:text-primary">This arbitration provision is made pursuant to a transaction involving interstate commerce and shall be governed by and enforceable under the FAA. The arbitrator will apply substantive law consistent with the FAA and applicable statutes of limitations. The arbitrator may award damages or other types of relief permitted by applicable substantive law, subject to the limitations set forth in this arbitration provision. The arbitrator will not be bound by judicial rules of procedure and evidence that would apply in a court. The arbitrator shall take steps to reasonably protect confidential information.</p>
    <p className="text-newblack/90 dark:text-primary">This arbitration provision shall survive (i) suspension, termination, revocation, closure, or amendments to these Terms of Use and the relationship of the parties; (ii) the bankruptcy or insolvency of any party hereto or other party; and (iii) any transfer of any securities, to any other party. If any portion of this arbitration provision is deemed invalid or unenforceable, the remaining portions of this arbitration provision shall nevertheless remain valid and in force. If arbitration is brought on a class, representative, or collective basis, and the limitations on such proceedings included herein are finally adjudicated to be unenforceable, then no arbitration shall be had. In no event shall any invalidation be deemed to authorize an arbitrator to determine Claims or make awards beyond those authorized in this arbitration provision.</p>
    <p className="text-newblack/90 dark:text-primary">If any provision of these Terms of Use conflicts with a provision contained in any subscription agreement, share transfer agreement or similar agreement to which you and Penthouse Finance are party, the terms of such other agreement shall control and shall be deemed to supercede the provisions of these Terms of Use.</p>
    <p className="text-newblack/90 dark:text-primary">Notwithstanding anything set forth in these Terms of Use, either Penthouse Finance or you may apply to any court of competent jurisdiction for injunctive relief without breach of the mandatory arbitration provisions set forth above.</p>
    <p className="text-newblack/90 dark:text-primary">THE PARTIES ACKNOWLEDGE THAT THEY HAVE A RIGHT TO LITIGATE CLAIMS THROUGH A COURT BEFORE A JUDGE, BUT WILL NOT HAVE THAT RIGHT IF ANY PARTY ELECTS ARBITRATION PURSUANT TO THIS ARBITRATION PROVISION. THE PARTIES HEREBY KNOWINGLY AND VOLUNTARILY WAIVE THEIR RIGHTS TO LITIGATE SUCH CLAIMS IN A COURT UPON ELECTION OF ARBITRATION BY ANY PARTY. THE PARTIES HERETO WAIVE A TRIAL BY JURY IN ANY LITIGATION RELATING TO THIS AGREEMENT, THE SHARES OR ANY OTHER AGREEMENTS RELATED THERETO. THIS WAIVER OF THE RIGHT TO A JURY TRIAL DOES NOT APPLY TO ANY CLAIMS MADE UNDER THE FEDERAL SECURITIES LAWS.</p>
    ‍<h3 className="dark:text-primary">Indemnify</h3>
    <p className="text-newblack/90 dark:text-primary">You agree to indemnify and hold the Company, its subsidiaries and affiliates, and each of their directors, officers, agents, contractors, members, managers, partners and employees, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney’s fees, arising out of or in connection with your User Content, any Third Party Content you post or share on or through the Site, your use of the Service or the Site, your conduct in connection with the Service or the Site or with other Users of the Service or the Site, or any violation of these Terms of Use or of any law or the rights of any third party. The previous sentence shall not apply to any extent to Users while acting as an investor or while registering as an investor in connection with their (i) posting of User Content or (ii) use of the Site or Service.</p>
    <h3 className="text-newblack/90 dark:text-primary">Other</h3>
    <p className="text-newblack/90 dark:text-primary">‍The failure of the Company to exercise or enforce any right or provision of these Terms of Use shall not constitute a waiver of such right or provision in that or any other instance. If any provision of these Terms of Use is held invalid, the remainder of these Terms of Use shall continue in full force and effect. If any provision of these Terms of Use shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Use and shall not affect the validity and enforceability of any remaining provisions.</p>
  </div>
  )

}


export default TermsandConditions
