


const TermsandConditions = () => { 
  return (<div>

    <h1 className="text-3xl font-bold text-center">Terms and Conditions</h1>
    <p>DATED: MAY 2022</p>
    <p>The Penthouse service and network (collectively, the “Service“) are operated by Penthouse Finance, and its affiliates (collectively, the “Company“, “we“, or “us“). By accessing or using our website at penthouse.finance including any subdomain thereof (the “Site“), you (the “User“) signify that you have read, understand and agree to be bound by these terms of use (“Terms of Use“), regardless of whether you are a registered member of the Service. In addition to these Terms of Use, you may enter into other agreements with us or others that will govern your use of the Service or related services offered by us or others. If there is any contradiction between these Terms of Use and another agreement you enter into applicable to specific aspects of the Service, the other agreement shall take precedence in relation to the specific aspects of the Service to which it applies. As used herein, “Users” means anyone who accesses and/or uses the Site. For any terms herein applicable to all Users, all investor members, or business and other entity Users specifically, or where the context otherwise requires, “Users” shall be deemed to include any business or other entity on behalf of which the Site or Service is accessed by any other User, and “you” shall be deemed to include any such business or other entity and any person acting on behalf of any such business or other entity in connection with the use of the Site or Service.</p>
    <h2>Changes to these Terms of Use</h2>
    <p>‍We may make changes to these Terms of Use from time to time. If we do this, we will post the changed Terms of Use on the Site and will indicate at the top of this page the date the Terms of Use were last revised. You understand and agree that your continued use of the Service or the Site after we have made any such changes constitutes your acceptance of the new Terms of Use.

    </p>
    
    <h1>TERMS APPLICABLE TO ALL USERS: ELIGIBILITY, LICENSE AND REPRESENTATIONS</h1>
    <h3>‍Eligibility: General</h3>
    <p>‍This Site is intended solely for Users who, if they are a natural person, are eighteen (18) years of age or older, and any registration by, use of or access to the Site by any natural person under 18 is unauthorized, unlicensed and in violation of these Terms of Use. By using the Service or the Site, you represent and warrant that, if you are a natural person, you are 18 or older and that you agree to and will abide by all of the terms and conditions of these Terms of Use. If you violate any of these Terms of Use, or otherwise violate an agreement between you and us, the Company may delete your profile and any content or information that you have posted on the Site and/or prohibit you from using or accessing the Service or the Site (or any portion, aspect or feature of the Service or the Site), at any time in its sole discretion, with or without notice, including without limitation if it believes that you are under 18.</p>
    <h3>‍License</h3>
    <h3>Proprietary Rights in Site Content; Limited License</h3>
    <p>The Website may include at any given time text, graphics, logos, icons, images, sound clips, video clips and data compilations, and together with the Website’s page layout, underlying code and software we refer to all of these as “Content”.</p>
    <p>All of the Content is the property of Penthouse Finance, our affiliates or third parties with whom we do business, and this means that it is protected by United States and international intellectual property laws and other relevant laws. This means that, except as provided by law, you may not reproduce, copy, distribute, store or in any other fashion re-use material from the Website unless otherwise indicated on the Website or unless given express written permission to do so by Penthouse Finance. For the avoidance of doubt, data mining or scraping the Website without the express written permission of Penthouse Finance is not permitted.</p>
    <h3>‍Restrictions on Data Collection/Termination</h3>
    <p>‍Without our prior consent, you may not:</p>
    <p>– use any automated means to access this Site or collect any information from the Site (including, without limitation, robots, spiders, scripts or other automatic devices or programs);
– frame the Site, utilize framing techniques to enclose any Content or other proprietary information, place pop-up windows over this Site’s pages, or otherwise affect the display of this Site’s pages; engage in the practices of “screen scraping”, “database scraping” or any other activity with the purpose of obtaining content or other information; or
-use this Site in any manner that violates applicable law or that could damage, disable, overburden, or impair this Site or interfere with any other party’s use and enjoyment of this Site.</p>
  
  <p>We may terminate, disable or throttle your access to, or use of, this Site and the Services for any reason, including without limitation, if we believe that you have violated or acted inconsistently with any portion of these Terms of Use.

      ‍User Representations</p>
    <p>You represent, warrant and agree that no materials of any kind submitted through your account or otherwise posted or shared by you through the Service will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libelous, defamatory or otherwise unlawful material. You further agree not to harvest or collect email addresses or other contact information of Users from the Service or the Site by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications. Additionally, you agree not to use automated scripts to collect information from the Service or the Site or for any other purpose. You further agree that you may not use the Service or the Site in any unlawful manner or in any other manner that could damage, disable, overburden or impair the Site. In addition, you agree not to use the Service or the Site to:</p>
    <p>– upload, post, transmit, share, store or otherwise make available any content that we deem to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;
– except where authorized by the Company, register for more than one User account, register for a User account on behalf of an individual other than yourself, operate a User account on behalf of or for the benefit of any person who is not eligible to register for or operate a User account in their own name, or register for a User account on behalf of any group or entity (other than approved investment accounts opened on behalf of legal entities);
– impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with or authority to act on behalf of any person or entity;
– upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising, solicitations, promotional materials, “junk mail”, “spam”, “chain letters”, “pyramid schemes”, or any other form of solicitation;
– upload, post, transmit, share, store or otherwise make publicly available on the Site any private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Security numbers and credit card numbers;
– solicit personal information from any natural person under 18 or solicit passwords or personally identifying information for commercial or unlawful purposes from any User;
– upload, post, transmit, share or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; intimidate or harass another User;
– upload, post, transmit, share, store or otherwise make available content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law;
– use or attempt to use another’s account, service or system without authorization from that person and the Company, or create a false identity on the Service or the Site; or
– upload, post, transmit, share, store or otherwise make available content that, in the sole judgment of the Company, is objectionable or which restricts or inhibits any other person from using or enjoying the Site, or which may expose the Company or its Users to any harm or liability of any type.</p>
<ul>
<li>&ndash; upload, post, transmit, share, store or otherwise make available any content that we deem to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;</li>
<li>&ndash; except where authorized by the Company, register for more than one User account, register for a User account on behalf of an individual other than yourself, operate a User account on behalf of or for the benefit of any person who is not eligible to register for or operate a User account in their own name, or register for a User account on behalf of any group or entity (other than approved investment accounts opened on behalf of legal entities);</li>
<li>&ndash; impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with or authority to act on behalf of any person or entity;</li>
<li>&ndash; upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising, solicitations, promotional materials, &ldquo;junk mail&rdquo;, &ldquo;spam&rdquo;, &ldquo;chain letters&rdquo;, &ldquo;pyramid schemes&rdquo;, or any other form of solicitation;</li>
<li>&ndash; upload, post, transmit, share, store or otherwise make publicly available on the Site any private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Security numbers and credit card numbers;</li>
<li>&ndash; solicit personal information from any natural person under 18 or solicit passwords or personally identifying information for commercial or unlawful purposes from any User;</li>
<li>&ndash; upload, post, transmit, share or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; intimidate or harass another User;</li>
<li>&ndash; upload, post, transmit, share, store or otherwise make available content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law;</li>
<li>&ndash; use or attempt to use another&rsquo;s account, service or system without authorization from that person and the Company, or create a false identity on the Service or the Site; or</li>
<li>&ndash; upload, post, transmit, share, store or otherwise make available content that, in the sole judgment of the Company, is objectionable or which restricts or inhibits any other person from using or enjoying the Site, or which may expose the Company or its Users to any harm or liability of any type.</li>
</ul>
    <h3>‍User Content Posted on the Site</h3>
    <p>‍You are solely responsible for the personal or business information, photos, profiles, messages, notes, text, information, music, video, contact information for you or others, advertisements or other content that you upload, publish, provide or display (hereinafter, “post“) on or through the Service or the Site, or transmit to or share with other Users (collectively the “User Content“). It is against the Terms of Use to contact members directly or to attempt to enter into any lending transactions with members outside of the Service. You understand and agree that the Company may, but is not obligated to, review and delete or remove (without notice) any User Content in its sole discretion, including without limitation, User Content that in the sole judgment of the Company violates these Terms of Use, might be offensive or illegal, or might violate the rights of, harm, or threaten the safety of, Users or others.</p>
    <p>By posting User Content to any part of the Site, you automatically grant, and you represent and warrant that you have the right to grant, to the Company an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with the right to sublicense) to use, copy, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part) and distribute such User Content for any purpose on or in connection with the Site or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize sublicenses of the foregoing. You may remove your User Content from the Site at any time. If you choose to remove your User Content, the license granted above will not expire.</p>
    <p>You may review personal or business information posted by other Users on the Site, but you are not authorized to disclose such information for any purpose.</p>
    <h3>ALL USERS: CONSENT TO ELECTRONIC TRANSACTIONS AND DISCLOSURES</h3>
    <p>‍Because Penthouse Finance operates on the Internet, it is necessary for you to consent to transact business with us online and electronically. As part of doing business with us, therefore, we also need you to consent to our giving you certain disclosures electronically, either via our Site or to the email address (or other electronic means of communication) you provide to us. By agreeing to the Terms of Use, you agree to receive electronically all documents, communications, notices, contracts, and agreements (including any IRS Forms, including Form 1099 and Form K-1) arising from or relating to your use of the Site and Service, including any securities you have purchased, your use of this Service, and the voting of any securities you have purchased as an investor in any offering made available through the Site (each, a “Disclosure“), whether we are acting in the capacity as issuer, agent or otherwise. The decision to do business with us electronically is yours. This document informs you of your rights concerning Disclosures.</p>
    <p>Electronic Communications. Any Disclosures will be provided to you electronically through Penthouse Finance either on our Site or via electronic mail to the verified email address you provided or through other electronic means of communication based on information provided by you. If you require paper copies of such Disclosures, you may write to us at the mailing address provided below and a paper copy will be sent to you at a cost of up to $5.00. A request for a paper copy of any Disclosure will not be considered a withdrawal of your consent to receive Disclosures electronically. Any IRS 1099 Forms or Form K-1s provided electronically will remain accessible through at least October 15 of the year in which such IRS Form 1099 or Form K-1 is made available; after that time the IRS Form 1099 may no longer be accessible electronically. We may discontinue electronic provision of Disclosures at any time in our sole discretion</p>
    <p>Scope of Consent. Your consent to receive Disclosures and transact business electronically, and our agreement to do so, applies to any transactions to which such Disclosures relate, whether between you and Penthouse Finance or between you and another party with whom you transact through the Site. Your consent will remain in effect for so long as you are a User and, if you are no longer a User, will continue until such a time as all Disclosures relevant to transactions that occurred while you were a User have been made.</p>
    <p>Consenting to Do Business Electronically. Before you decide to do business electronically with Penthouse Finance, you should consider whether you have the required hardware and software capabilities described below.</p>
    <p>Hardware and Software Requirements. In order to access and retain Disclosures electronically, you must satisfy the following computer hardware and software requirements: access to the Internet; an email account and related software capable of receiving email through the Internet; supported Web browsing software (Chrome version 32.0 or higher, Firefox version 26.0 or higher, Internet Explorer version 8.0 or higher, or Safari version 7.0 or higher); and hardware capable of running this software.</p>
    <p>Telephone Consumer Protection Act Overview Consent: You expressly consent to receiving calls and messages, including auto-dialed and pre-recorded message calls, and SMS messages (including text messages) from us, our affiliates, agents and others calling at their request or on their behalf, at any telephone numbers that you have provided or may provide in the future (including any cellular telephone numbers). Your cellular or mobile telephone provider will charge you according to the type of plan you carry.</p>
    <p>Consent to Digital Call Recording. Penthouse Finance uses technology that records telephone calls for quality assurance, customer service, training and data analysis purposes only. By agreeing to our Terms of Use, you hereby consent to our recording of telephone conversations between you and Penthouse Finance representatives and you hereby agree that our employees and authorized representatives may listen to a call that has been recorded on our behalf for the purposes set forth above.</p>
    <p>To unsubscribe from text messages at any time reply STOP, STOP ALL, UNSUBSCRIBE, CANCEL, END or QUIT to any text message you receive from Penthouse Finance. You consent that following such a request to unsubscribe, you may receive one final text message from Penthouse Finance confirming your request. Note that unsubscribing from promotional and/or account-related texts will not prevent Penthouse Finance from sending you text messages for security and authentication purposes.</p>
    <p>Additional Mobile Technology Requirements. If you are accessing our site and the Disclosures electronically via a mobile device (such as a smart phone, tablet, and the like), in addition to the above requirements you must make sure that you have software on your mobile device that allows you to print and save the Disclosures presented to you during the application process. These applications can be found for most mobile devices in the device’s respective “app store”. If you do not have these capabilities on your mobile device, please access our site through a device that provides these capabilities.</p>
    <p>Withdrawing Consent. You may not withdraw consent to doing business with us electronically for as long as you have outstanding any investments made through the Site. If you have no outstanding investments made through the site and wish to withdraw consent to doing business electronically, we will terminate your registered user account with us.</p>
    <p>How to Contact Us regarding Electronic Disclosures. You can contact us via email at hello@penthouse.finance</p>
    <p>If you are an individual User, you will keep us informed of any change in your email or home mailing address so that you can continue to receive all Disclosures in a timely fashion. If your registered email address changes, you must notify us of the change by sending an email to hello@penthouse.finance. You also agree to update your registered residence address and telephone number on the Site if they change. If you are a business or entity User or are acting on behalf of a business or entity, you will keep us informed of any change to your email address, telephone number and primary business address, as discussed under “Terms Applicable to Business and Other Entity Users” below.</p>
  </div>)

}


export default TermsandConditions
